// Backward-compatible re-exports. Prefer importing from './validation' for new code.
export {
  isValidEmail,
  isValidPhoneIntl as isValidPhone,
  isValidPhoneIN,
  isValidGstin,
  isValidPan,
  isValidPincode,
  isValidIfsc,
  isValidUpi,
  isValidVehicleNo,
  isValidUsername,
  isPositiveAmount,
  isNonNegativeAmount,
  emailError,
  phoneINError,
  gstinError,
  panError,
  pincodeError,
  ifscError,
  upiError,
  amountError,
  required,
  PATTERNS,
} from './validation';
